trigger:
- master

jobs:

- job: Pipeline
  strategy:
    matrix:
      linux:
        python.version: '3.7'
        imageName: 'ubuntu-16.04'
      windows:
        python.version: '3.7'
        imageName: 'vs2017-win2016'
    maxParallel: 4

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
    inputs:
      keyfile: 'poetry.lock'
      # two sources of delay in repeat builds: poetry install and dependency install
      # we manage the .poetry venv and that's where poetry gets installed
      # poetry manages .venv
      # both are relative to the root because that's a current requirement of the
      #  RestoreAndSaveCache plugin.
      targetfolder: '.venv, .poetry'
      vstsFeed: '$(CacheArtifactFeedId)'
    displayName: 'PyPI Cache Restore'

  - script: |
      python -m venv .poetry
      .poetry/bin/python -m pip install --upgrade pip
      .poetry/bin/python -m pip install --upgrade poetry
      .poetry/bin/python -m poetry config settings.virtualenvs.in-project true
      .poetry/bin/python -m poetry config settings.virtualenvs.path .venv
    displayName: 'Poetry setup'

  - script: |
      .poetry/bin/python -m poetry install
    displayName: 'Install/update dependencies'

    # If dependency resolution succeeded, cache.
  - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
    inputs:
      keyfile: 'poetry.lock'
      targetfolder: '.venv, .poetry'
      vstsFeed: '$(CacheArtifactFeedId)'
    displayName: 'PyPI Cache Save'

  - script: |
      .poetry/bin/python -m poetry run pytest -s -ra --junitxml=junit/test-results.xml tests
    displayName: Run tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version) $(Agent.OS)'
    condition: succeededOrFailed()
    displayName: Publish test results

    # In lieu of getting logs as attachments on the test summary, we
    # publish as artifacts.
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'test_logs_$(python.version)_$(Agent.OS)'
      targetPath: logs/
    condition: succeededOrFailed()
    displayName: Publish logs

  - script: poetry build
    displayName: Build
  
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'artifacts_$(python.version)_$(Agent.OS)'
      targetPath: dist/
    displayName: Publish artifacts
